version: '3'

services:
  postgresdb:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    container_name: nest-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - ./postgres:/var/lib/postgresql/data
  